#! /bin/sh

#
# bspwm startup
# 

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor VGA1 -d I II III IV V VI
bspc monitor LVDS1 -d VII VIII IX X

bspc monitor LVDS1 -s VGA1

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#
# custom startup
#

# keyboard layout
setxkbmap -layout br -variant abnt2

# monitor setup
#xrandr --output LVDS1 --off --output VGA1 --mode 1360x768 --rotate normal --primary
#xrandr --output LVDS1 --mode 1024x768 --output VGA1 --primary --mode 1024x768 --rotate normal
xrandr --output LVDS1 --mode 1366x768 --rotate normal --output VGA1 --primary --mode 1360x768 --rotate normal --left-of LVDS1

# background wallpaper
#feh --bg-scale ~/Pictures/Wallpapers/wallhaven-d6gzrj.jpg
feh --bg-scale ~/Pictures/Wallpapers/1361249-Lain-IwakuraLain-Iwakura.png ~/Pictures/Wallpapers/Serial-Experiments-Lain-cyberpunk-1905541-wallhere.com.jpg

# transparent windows
picom &

# print screen/area daemon
flameshot &

